In [46]:
from torch_geometric.datasets import Planetoid, MovieLens, MovieLens100K, OGB_MAG

In [47]:
import torch

In [48]:
from torch_geometric.loader import LinkNeighborLoader

In [49]:
data = Planetoid("dataset/", name='Cora')[0]

In [50]:
data

Data(x=[2708, 1433], edge_index=[2, 10556], y=[2708], train_mask=[2708], val_mask=[2708], test_mask=[2708])

In [51]:
data.edge_index

tensor([[   0,    0,    0,  ..., 2707, 2707, 2707],
        [ 633, 1862, 2582,  ...,  598, 1473, 2706]])

In [52]:
loader = LinkNeighborLoader(data, num_neighbors=[4]*2, batch_size=4, disjoint=True)

In [53]:
load_iter = iter(loader)

In [54]:
sampled_data = next(load_iter)

In [55]:
sampled_data

Data(x=[76, 1433], edge_index=[2, 104], y=[76], train_mask=[76], val_mask=[76], test_mask=[76], n_id=[76], e_id=[104], batch=[76], input_id=[4], edge_label_index=[2, 8])

In [56]:
def label_scan(edge_index, batch, n_edges):
    
    label_list = [float('inf')] * len(batch)
    for i in range(2):
        for j in range(n_edges):
            label_list[(i * n_edges) + j] = i
    for i in range(len(edge_index[0])):
        v = edge_index[0][i]
        u = edge_index[1][i]
        if v > u:
            label_list[v] = min(label_list[u] + 2, label_list[v])
    
    return label_list

In [57]:
torch.tensor(label_scan(sampled_data.edge_index, sampled_data.batch, 4))

tensor([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
        4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5])

In [58]:
sampled_data

Data(x=[76, 1433], edge_index=[2, 104], y=[76], train_mask=[76], val_mask=[76], test_mask=[76], n_id=[76], e_id=[104], batch=[76], input_id=[4], edge_label_index=[2, 8])

In [59]:
sampled_data.edge_index

tensor([[ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
         26, 27, 28, 29, 30, 31, 32, 33, 10,  0, 34, 35, 36,  0, 34,  8,  0, 37,
         13,  1, 38, 39, 40,  1, 38, 11,  1, 41, 16,  2, 42, 43, 44,  2, 42, 14,
          2, 45, 46, 47, 48, 49,  3,  3, 50,  4, 22, 51,  4, 52, 53, 54, 55, 56,
          5, 24, 57,  5, 58, 23, 59, 60, 61, 62,  5,  6, 28, 63, 64, 27, 65,  6,
          6, 66,  7, 67, 68,  7, 69,  7, 70, 71, 72, 73, 74, 75],
        [ 0,  0,  0,  1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,  5,
          5,  6,  6,  6,  7,  7,  7,  7,  8,  8,  8,  8,  9,  9,  9, 10, 10, 10,
         11, 11, 11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14, 14, 15, 15, 15, 16,
         16, 16, 17, 17, 17, 17, 18, 19, 19, 20, 20, 21, 21, 21, 22, 22, 22, 22,
         23, 23, 23, 24, 24, 24, 25, 25, 25, 25, 26, 27, 27, 27, 27, 28, 28, 28,
         29, 29, 30, 30, 30, 31, 32, 32, 32, 32, 33, 33, 33, 33]])

In [60]:
sampled_data.x

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [61]:
int(sampled_data.batch.max()) + 1

4

In [62]:
sampled_data.e_id

tensor([    0,     1,     2,     0,     1,     2,     0,     1,     2,     3,
            4,     5,  2569,  2570,  2571,  7565,  7566,  7567,  7568, 10306,
        10307, 10308,     7,     8,     6,    10,  7565,  7566,  7567,  7568,
         2569,  2570,  2571, 10306, 10307, 10308,  7565,  7566,  7567,  7568,
         2569,  2570,  2571, 10306, 10307, 10308,  7565,  7566,  7567,  7568,
         2569,  2570,  2571, 10306, 10307, 10308,     6,     8,     9,    10,
         2643,  2640,  2641,  7578,  7579,     0,     1,     2,  6771,  6777,
         6759,  6742, 10306, 10307, 10308,     0,     1,     2,  6798,  6785,
         6731,  6755,  3637,  7565,  7566,  7567,  7568,     0,     1,     2,
         4550,  4551,     3,     4,     5,  5774,  6597,  6598,  6601,  6602,
         1383,  1382,  1385,  1386])

In [63]:
sampled_data.edge_label_index

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [64]:
(sampled_data.batch == 0).nonzero().ravel()

tensor([ 0,  4,  8,  9, 10, 20, 21, 22, 34, 35, 36, 37, 51, 52, 53, 54, 55, 56])

In [65]:
het_data = MovieLens100K("dataset/")[0]

In [66]:
het_data

HeteroData(
  movie={ x=[1682, 18] },
  user={ x=[943, 24] },
  (user, rates, movie)={
    edge_index=[2, 80000],
    rating=[80000],
    time=[80000],
    edge_label_index=[2, 20000],
    edge_label=[20000]
  },
  (movie, rated_by, user)={
    edge_index=[2, 80000],
    rating=[80000],
    time=[80000]
  }
)

In [67]:
edge_type = list(het_data.edge_index_dict.keys())[0]

In [68]:
edge_type

('user', 'rates', 'movie')

In [69]:
het_data[edge_type].edge_index

tensor([[   0,    0,    0,  ...,  942,  942,  942],
        [   0,    1,    2,  ..., 1187, 1227, 1329]])

In [70]:
(edge_type, het_data[edge_type].edge_index)

(('user', 'rates', 'movie'),
 tensor([[   0,    0,    0,  ...,  942,  942,  942],
         [   0,    1,    2,  ..., 1187, 1227, 1329]]))

In [71]:
het_loader = LinkNeighborLoader(het_data, num_neighbors=[4]*2, batch_size=4, disjoint=True, edge_label_index=edge_type)

In [72]:
het_loader_iter = iter(het_loader)

In [73]:
slicer = next(het_loader_iter)

In [74]:
slicer

HeteroData(
  movie={
    x=[82, 18],
    n_id=[82],
    batch=[82]
  },
  user={
    x=[84, 24],
    n_id=[84],
    batch=[84]
  },
  (user, rates, movie)={
    edge_index=[2, 80],
    rating=[80],
    time=[80],
    edge_label_index=[2, 4],
    e_id=[80],
    input_id=[4]
  },
  (movie, rated_by, user)={
    edge_index=[2, 80],
    rating=[80],
    time=[80],
    e_id=[80]
  }
)

In [75]:
slicer

HeteroData(
  movie={
    x=[82, 18],
    n_id=[82],
    batch=[82]
  },
  user={
    x=[84, 24],
    n_id=[84],
    batch=[84]
  },
  (user, rates, movie)={
    edge_index=[2, 80],
    rating=[80],
    time=[80],
    edge_label_index=[2, 4],
    e_id=[80],
    input_id=[4]
  },
  (movie, rated_by, user)={
    edge_index=[2, 80],
    rating=[80],
    time=[80],
    e_id=[80]
  }
)

In [76]:
slicer.node_types

['movie', 'user']

In [77]:
slicer["user"].batch

tensor([0, 1, 2, 3, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [78]:
slicer.edge_index_dict

{('user',
  'rates',
  'movie'): tensor([[ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
          22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
          40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
          58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
          76, 77, 78, 79, 80, 81, 82, 83],
         [ 0,  0,  0,  0,  1,  1,  1,  1,  2,  2,  2,  2,  3,  3,  3,  3,  4,  4,
           4,  4,  5,  5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,  8,  8,  8,  8,
           9,  9,  9,  9, 10, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12, 12, 13, 13,
          13, 13, 14, 14, 14, 14, 15, 15, 15, 15, 16, 16, 16, 16, 17, 17, 17, 17,
          18, 18, 18, 18, 19, 19, 19, 19]]),
 ('movie',
  'rated_by',
  'user'): tensor([[ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
          22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 30, 32, 33, 34, 35, 36, 37, 38,
          39, 40, 41, 42,

In [79]:
from torch_geometric.nn.models.igmc import igmc_node_label

In [80]:
slicer['movie'].batch

tensor([0, 1, 2, 3, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [81]:
slicer.node_types

['movie', 'user']

In [82]:
igmc_node_label(slicer, 4, edge_type)

HeteroData(
  movie={
    x=[82, 18],
    n_id=[82],
    batch=[82],
    igmc_id=[82]
  },
  user={
    x=[84, 24],
    n_id=[84],
    batch=[84],
    igmc_id=[84]
  },
  (user, rates, movie)={
    edge_index=[2, 80],
    rating=[80],
    time=[80],
    edge_label_index=[2, 4],
    e_id=[80],
    input_id=[4]
  },
  (movie, rated_by, user)={
    edge_index=[2, 80],
    rating=[80],
    time=[80],
    e_id=[80]
  }
)

In [148]:
import torch
from torch_geometric.data import HeteroData
from torch_geometric.loader import LinkNeighborLoader
data = HeteroData()

data['user'].x = torch.arange(6)
data['movie'].x = torch.arange(6, 13)

data['user', 'movie'].edge_index = torch.stack([torch.tensor([0,0,0,1,2,2,2,3,3,3,4,5]), torch.tensor([0,1,2,0,0,5,6,0,3,4,2,2]) ])
data['movie', 'user'].edge_index = torch.stack([torch.tensor([0,0,0,0,1,2,2,2,3,4,5,6]), torch.tensor([0,1,2,3,0,0,4,5,3,3,2,2]),])
test_loader = LinkNeighborLoader(data, num_neighbors=[-1]*2, batch_size=1, disjoint=True, edge_label_index=(('user', 'to', 'movie'), torch.tensor([[0], [0]])))
test_batch = next(iter(test_loader))

In [147]:
data

HeteroData(
  user={ x=[6] },
  movie={ x=[7] },
  (user, to, movie)={ edge_index=[2, 12] },
  (movie, to, user)={ edge_index=[2, 12] }
)

In [139]:
test_batch = next(iter(test_loader))

In [140]:
test_batch

HeteroData(
  user={
    x=[10],
    n_id=[10],
    batch=[10]
  },
  movie={
    x=[10],
    n_id=[10],
    batch=[10]
  },
  (user, to, movie)={
    edge_index=[2, 12],
    e_id=[12],
    input_id=[1],
    edge_label_index=[2, 1]
  },
  (movie, to, user)={
    edge_index=[2, 13],
    e_id=[13]
  }
)

In [141]:
test_batch["user"].n_id

tensor([0, 0, 1, 2, 3, 1, 2, 3, 4, 5])

In [142]:
test_batch[("user", "to", "movie")].edge_index

tensor([[1, 2, 3, 4, 0, 5, 6, 7, 0, 0, 8, 9],
        [0, 0, 0, 0, 1, 1, 1, 1, 2, 3, 3, 3]])

In [143]:
test_batch[("user", "to", "movie")].e_id

tensor([0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 7])

In [145]:
test_batch[("movie", "to", "user")].edge_index

tensor([[1, 2, 3, 0, 4, 5, 0, 0, 6, 7, 0, 8, 9],
        [0, 0, 0, 1, 1, 1, 2, 3, 3, 3, 4, 4, 4]])

In [89]:
res_batch = igmc_node_label(test_batch, 4, edge_direction=('paper', 'to', 'author'))

In [90]:
res_batch['paper'].igmc_id

tensor([0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4,
        4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4])